# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

source: 
destination: _site
sass:
  sass_dir: _sass
  style: expanded # compressed # expanded

# permalink and highlighter
permalink   : /:title/
markdown    : kramdown
highlighter : rouge

# SEO settings
title: Boroondara Bicycle Strategy 2018
description: "Information for the unofficial bicycle strategy for Boroondara"
keywords: "Boroondara, bicycle, strategy, 2018, bike"

# Site settings
url: https://boroondarabike.github.io
# baseurl: ""
# baseurl: ""

# Author settings
author:
  name      : Philip Mallis
  job       : 
  bio       : "Map lover, bike rider and urban planner."
  thumb     : /images/author.jpg
  email     : 
  url       : http://philipmallis.com
  github    : http://github.com/philam
  twitter   : http://twitter.com/philipmallis
  facebook  : 
  linkedin  : http://linkedin.com/in/philipmallis

# google_analytics: UA-52446115-1
repo: https://github.com/boroondarabike/boroondarabike.github.io

# comments
disqus_shortname: "boroondarabike"

# pages
include: ["_pages"] 
        
